spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wzs?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
 
  mybatis:
    mapper-locations: classpath*:/mybatis/**mapper.xml
    typeAliasesPackage: wzs.wzstest.mapper
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
    
    